#!/usr/bin/env bash
# Blocks obvious AI attribution/tell phrases in git commit messages.
# Usage as git hook: cp block-ai-attribution.sh .git/hooks/commit-msg

set -euo pipefail

MSG_FILE="${1:-}"

if [ -n "$MSG_FILE" ] && [ -f "$MSG_FILE" ]; then
  message=$(cat "$MSG_FILE")
else
  message=$(cat -)
fi

[ -z "$message" ] && exit 0

PATTERNS='(co-authored-by:.*(claude|chatgpt|gpt|copilot)|generated by (ai|claude|chatgpt|copilot)|ai-generated|created with (claude|chatgpt|copilot)|written by (claude|chatgpt|ai)|as an ai language model|i am an ai|i'\''m an ai|this (commit|change|code) was generated)'

if echo "$message" | grep -qiE "$PATTERNS"; then
  cat >&2 <<'EOF'
Commit blocked: AI attribution/tell phrase found.

Remove generated-by/co-authored-by AI text and rewrite the message in the
project's normal commit style before committing.
EOF
  exit 1
fi

exit 0
