#!/usr/bin/env bash
# Lightweight smoke tests for Agent Security Kit.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ok() { printf 'ok %s\n' "$1"; }

find components -type f -name '*.sh' -print0 | xargs -0 -n1 bash -n
ok "shell syntax"

secret_payload='{"tool_name":"write_file","tool_input":{"content":"token=sk-ant-api03-aaaaaaaaaaaaaaaaaaaaaaaa"}}'
clean_payload='{"tool_name":"write_file","tool_input":{"content":"hello world"}}'

out=$(printf '%s\n' "$secret_payload" | bash components/hermes/hermes-egress-guard/block-secrets.sh)
echo "$out" | grep -q '"decision":"block"'

out=$(printf '%s\n' "$clean_payload" | bash components/hermes/hermes-egress-guard/block-secrets.sh)
[ "$out" = '{}' ]
ok "egress guard"

bad_cmd='{"tool_name":"terminal","tool_input":{"command":"rm -rf /"}}'
good_cmd='{"tool_name":"terminal","tool_input":{"command":"ls -la"}}'

out=$(printf '%s\n' "$bad_cmd" | bash components/hermes/hermes-safe-terminal/block-destructive.sh)
echo "$out" | grep -q '"decision":"block"'

out=$(printf '%s\n' "$good_cmd" | bash components/hermes/hermes-safe-terminal/block-destructive.sh)
[ "$out" = '{}' ]
ok "safe terminal"

msg_file=$(mktemp)
printf 'feat: update module\n\nGenerated by AI\n' > "$msg_file"
if bash components/hermes/hermes-commit-guard/block-ai-attribution.sh "$msg_file" >/tmp/ask-commit.out 2>/tmp/ask-commit.err; then
  echo "commit guard missed AI attribution" >&2
  exit 1
fi
printf 'feat: update module\n' > "$msg_file"
bash components/hermes/hermes-commit-guard/block-ai-attribution.sh "$msg_file"
ok "commit attribution guard"

tmp_repo=$(mktemp -d)
printf 'readme\nmore\nlines\nfor\ncheck\n' > "$tmp_repo/README.md"
printf 'MIT\n' > "$tmp_repo/LICENSE"
printf 'token=sk-ant-api03-aaaaaaaaaaaaaaaaaaaaaaaa\n' > "$tmp_repo/app.sh"
if bash components/hermes/hermes-publish-gate/publish-gate.sh "$tmp_repo" >/tmp/ask-gate.out 2>&1; then
  echo "publish gate missed fake secret" >&2
  exit 1
fi
grep -q 'Secret scan (files).*FAIL' /tmp/ask-gate.out
ok "publish gate detects secret"

scan_dir=$(mktemp -d)
printf 'token=sk-ant-api03-aaaaaaaaaaaaaaaaaaaaaaaa\n' > "$scan_dir/config.sh"
if bash components/hermes/hermes-workspace-scanner/scan-workspace.sh "$scan_dir" >/tmp/ask-scan.out 2>&1; then
  echo "workspace scanner missed fake secret" >&2
  exit 1
fi
grep -q 'SECRETS FOUND' /tmp/ask-scan.out
ok "workspace scanner detects secret"

printf 'all smoke tests passed\n'
